CREATE DATABASE RESTAURANT;
USE RESTAURANT;

CREATE TABLE PRODUCTOS{
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO_PROD VARCHAR(50) NOT NULL,
    DESCRIPCION_PROD VARCHAR(100) NOT NULL,
    PRECIO FLOAT(6,2) NOT NULL,
    IMAGEN VARCHAR(100) NOT NULL,
    INGREDIENTES VARCHAR(200) NOT NULL
};
INSERT INTO PRODUCTOS (TITULO_PROD,DESCRIPCION_PROD,IMAGEN,INGREDIENTES,PRECIO) VALUES
('Ceviche Mix', 'Disfruta la frescura y sabor que caracteriza a nuestro ceviche', '/imagen/6.jpeg', 'Pescado fresco, Limón, Cebolla, Cilantro', 10.00),
('Yakisoba', 'Llena tu semana de sabor con nuestros Yakisobas', '/imagen/42.jpeg', 'Fideos, Vegetales, Salsa de soya, Carne', 12.00);

CREATE TABLE CLIENTE{
    CI INT(15) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    CORREO VARCHAR(50) DEFAULT " ",
    TELEFONO INT(10) NOT NULL
};
CREATE TABLE ADMINISTRADOR{
    NIT INT(15) NOT NULL PRIMARY KEY,
    NOMBRE_ADM VARCHAR(50) NOT NULL,
    APELLIDO_ADM VARCHAR(50) NOT NULL,
    CORREO VARCHAR(50) NOT NULL
};
CREATE TABLE CAJERO{
    ID_CAJERO INT(10) NOT NULL PRIMARY KEY,
    NOMBRE_CAJERO VARCHAR(50) NOT NULL,
    APELLIDO_CAJERO VARCHAR(50) NOT NULL,


};
CREATE TABLE ORDEN{
    ID_ORDEN INT AUTO_INCREMENT PRIMARY KEY,
    CI INT(15) NOT NULL,
    ID_CAJERO INT(10) NOT NULL,
    FECHA_ORDEN DATETIME DEFAULT NOW(),
    STATUS VARCHAR(35) DEFAULT "PENDIENTE"
    FOREIGN KEY (CI) REFERENCES CLIENTE(CI),
    FOREIGN KEY (ID_CAJERO) REFERENCES CAJERO(ID_CAJERO)
};
CREATE TABLE ORDEN_DETALLES{
    ID_COMPRA_DETALLES INT AUTO_INCREMENT PRIMARY KEY,
    ID_ORDEN INT NOT NULL,
    ID_BEBIDA INT,
    ID_COMIDA INT,
    CANTIDAD INT(10) NOT NULL,
    PRECIO_TOTAL FLOAT(6,2) NOT NULL,
    FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN(ID_ORDEN),
    FOREIGN KEY (ID_BEBIDA) REFERENCES BEBIDAS(ID_BEBIDA)
    FOREIGN KEY (ID_COMIDA) REFERENCES COMIDA(ID_COMIDA)

};


