CREATE DATABASE RESTAURANT;
USE RESTAURANT;

CREATE TABLE BEBIDAS{
    ID_BEBIDA INT AUTO_INCREMENT PRIMARY KEY,
    TITULO_BEBIDA VARCHAR(50) NOT NULL,
    DESCRIPCION_BEBIDA VARCHAR(100) NOT NULL,
    PRECIO_BEBIDA FLOAT(6,2) NOT NULL,
    RUTA_BEBIDA VARCHAR(100) NOT NULL,
    TAGS VARCHAR(30) NOT NULL
};
INSERT INTO BEBIDAS (TITULO_BEBIDA, DESCRIPCION_BEBIDA, PRECIO_BEBIDA, RUTA_BEBIDA, TAGS)
VALUES ('Coctel Emperatriz', 'Infusion de rosas, vermouth blanco nacional, soju,sour de naranja', 50, '/imagen/21.jpeg', '1');

CREATE TABLE COMIDA{
    ID_COMIDA INT AUTO_INCREMENT PRIMARY KEY,
    TITULO_COMIDA VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRECIO_COMIDA FLOAT(6,2) NOT NULL,
    RUTA_COMIDA VARCHAR(100) NOT NULL,
    TAGS VARCHAR(30) NOT NULL
};
CREATE TABLE CLIENTE{
    CI INT(15) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    CORREO VARCHAR(50) DEFAULT " ",
    TELEFONO INT(10) NOT NULL
};
CREATE TABLE ADMINISTRADOR{
    NIT INT(15) NOT NULL PRIMARY KEY,
    NOMBRE_ADM VARCHAR(50) NOT NULL,
    APELLIDO_ADM VARCHAR(50) NOT NULL,
    CORREO VARCHAR(50) NOT NULL
};
CREATE TABLE CAJERO{
    ID_CAJERO INT(10) NOT NULL PRIMARY KEY,
    NOMBRE_CAJERO VARCHAR(50) NOT NULL,
    APELLIDO_CAJERO VARCHAR(50) NOT NULL,


};
CREATE TABLE ORDEN{
    ID_ORDEN INT AUTO_INCREMENT PRIMARY KEY,
    CI INT(15) NOT NULL,
    ID_CAJERO INT(10) NOT NULL,
    FECHA_ORDEN DATETIME DEFAULT NOW(),
    STATUS VARCHAR(35) DEFAULT "PENDIENTE"
    FOREIGN KEY (CI) REFERENCES CLIENTE(CI),
    FOREIGN KEY (ID_CAJERO) REFERENCES CAJERO(ID_CAJERO)
};
CREATE TABLE ORDEN_DETALLES{
    ID_COMPRA_DETALLES INT AUTO_INCREMENT PRIMARY KEY,
    ID_ORDEN INT NOT NULL,
    ID_BEBIDA INT,
    ID_COMIDA INT,
    CANTIDAD INT(10) NOT NULL,
    PRECIO_TOTAL FLOAT(6,2) NOT NULL,
    FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN(ID_ORDEN),
    FOREIGN KEY (ID_BEBIDA) REFERENCES BEBIDAS(ID_BEBIDA)
    FOREIGN KEY (ID_COMIDA) REFERENCES COMIDA(ID_COMIDA)

};


